version: '3'
services:
  zookeeper:
    container_name: experimental-zookeeper
    image: wurstmeister/zookeeper
    hostname: zookeeper
    ports:
      - 2181:2181

  kafka:
    container_name: experimental-kafka
    image: wurstmeister/kafka
    hostname: kafka
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ADVERTISED_PORT: 9092
      AUTO_CREATE_TOPICS: 'true'
      KAFKA_ZOOKEEPER_CONNECT: 'host.docker.internal:2181'
    ports:
      - 9092:9092
    depends_on:
      - zookeeper