version: '3'
services:
  zookeeper:
    container_name: zookeeper
    image: wurstmeister/zookeeper
    hostname: zookeeper
    ports:
      - 2181:2181

  kafka:
    container_name: kafka
    image: wurstmeister/kafka
    hostname: kafka
    environment:
      AUTO_CREATE_TOPICS: 'true'
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: LOCAL_HOST://:9092,DOCKER://:29092
      KAFKA_ADVERTISED_LISTENERS: LOCAL_HOST://localhost:9092,DOCKER://kafka:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LOCAL_HOST:PLAINTEXT,DOCKER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LOCAL_HOST
    ports:
      - 9092:9092
      - 29092:29092
    depends_on:
      - zookeeper

  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    ports:
      - 8080:8080
    depends_on:
      - zookeeper
      - kafka
    #    restart: always
    environment:
      KAFKA_CLUSTERS_0_NAME: clusterName
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181