server:
  port: 9091
spring:
  datasource:
    url: jdbc:postgresql://localhost:7432/loyalty-db
    username: loyalty-db
    password: 12345678
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      connection-timeout: 15000
      max-lifetime: 1800000
      maximum-pool-size: 15
      minimum-idle: 3
      pool-name: api-pool
    jpa:
      properties:
        hibernate:
          jdbc:
            time_zone: UTC
            lob:
              non_contextual_creation: true
          # форматирует запросы, генерируемые Hibernate при выводе их в лог
          format_sql: true
  kafka:
    bootstrap-servers: localhost:9092
    producer:
#      transaction-id-prefix: someTransactionPrefix
      properties:
        #        transaction.timeout.ms: 12000
        #        enable.idempotence: true
        key-serializer: org.apache.kafka.common.serialization.StringDeserializer
        value-serializer: org.apache.kafka.common.serialization.StringDeserializer